### ISSUE TITLE
Error "Please add a @NgModule annotation" in Angular 5

### ISSUE THREAD

**Issue by psathish18** [kageoni/ng2-modal-module#1]
I am using ng2-modal-module in my project angular v4. now I have migrated to angular 5.2.5 but looks like ng2-module-module works only till <=4.  Can you fix this issue ?

> error: Unexpected value 'ModalModule' imported by the module 'AppModule'. Please add a @NgModule annotation.

refer [Error "Please add a @NgModule annotation" in Angular 5](https://github.com/angular/angular/issues/15763)

**Comment by kageoni** [comment]
please check the new version 1.0.1 of this module: [https://www.npmjs.com/package/ng2-modal-module/v/1.0.1](https://www.npmjs.com/package/ng2-modal-module/v/1.0.1).
It works with the Bootstrap 3.* versions. NOT tested with Bootstrap 4!
